name: khazana_app
description: "A Flutter Mutual Fund Watchlist & Performance Analytics App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  # Authentication
  supabase_flutter: ^2.8.4
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.2
  # UI Components
  fl_chart: ^0.70.2
  flutter_heatmap_calendar: ^1.0.5
  shimmer: ^3.0.0
  # Utilities
  intl: ^0.20.2
  path_provider: ^2.1.5
  http: ^1.3.0
  json_annotation: ^4.9.0
  # Icons and UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  uuid: ^4.5.1
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  go_router: ^14.8.1
  logger: ^2.5.0
  ndialog: ^4.4.1+1
  freezed_annotation: ^3.0.0
  flutter_slidable: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Code Generation
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  hive_generator: ^2.0.1
  freezed: ^3.0.4

dependency_overrides:
  source_gen: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
