name: khazana_app
description: "A Flutter Mutual Fund Watchlist & Performance Analytics App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  # Authentication
  supabase_flutter: ^2.3.4
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  # UI Components
  fl_chart: ^0.66.2
  flutter_heatmap_calendar: ^1.0.5
  shimmer: ^3.0.0
  # Utilities
  intl: ^0.19.0
  path_provider: ^2.1.2
  http: ^1.2.0
  json_annotation: ^4.8.1
  # Icons and UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  uuid: ^4.5.1
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  go_router: ^14.8.1
  logger: ^2.5.0
  ndialog: ^4.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Code Generation
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
